export const LOCAL_STORAGE_COLLECT_WORD_IS_ANIMATED =
    "LOCAL_STORAGE_COLLECT_WORD_IS_ANIMATED";

export const LOCAL_STORAGE_COLLECT_WORD_SELECTED_LANGUAGE =
    "LOCAL_STORAGE_COLLECT_WORD_SELECTED_LANGUAGE";

export const LOCAL_STORAGE_DRAG_CARD_SELECTED_LANGUAGE =
    "LOCAL_STORAGE_DRAG_CARD_SELECTED_LANGUAGE";

export const USER_LOCALSTORAGE_KEY = 'user';
export const LOCAL_STORAGE_THEME_KEY = 'theme';
